#!/usr/bin/env python3
"""Regenerates two synthetic DIVA environmental grids (fixtures/grids/*.gri|grd) and postgres/fixtures-env.sql.
Values are linear in lat/lon so tests can compute the expected value at any cell centre:
  e2e_temp = 20 + 0.4 * (lat + 27)      (el9001, degrees C)
  e2e_rain = 500 + 10 * (lon - 112)     (el9002, mm)"""
import os, struct
HERE = os.path.dirname(os.path.abspath(__file__))
X0, X1, Y0, Y1, RES = 112.0, 154.0, -44.0, -10.0, 0.25
ncols, nrows = round((X1 - X0) / RES), round((Y1 - Y0) / RES)
FUNCS = {'e2e_temp': lambda lat, lon: 20 + 0.4 * (lat + 27), 'e2e_rain': lambda lat, lon: 500 + 10 * (lon - 112)}
UNITS = {'e2e_temp': 'degrees C', 'e2e_rain': 'mm'}
for name, f in FUNCS.items():
    vals = [f(Y1 - (r + 0.5) * RES, X0 + (c + 0.5) * RES) for r in range(nrows) for c in range(ncols)]  # row 0 = north
    with open(os.path.join(HERE, 'grids', name + '.gri'), 'wb') as g:
        g.write(struct.pack('<%df' % len(vals), *vals))
    hdr = ("[General]\r\nTitle=%s\r\n[GeoReference]\r\nProjection=GEOGRAPHIC\r\nDatum=WGS84\r\nMapunits=DEGREES\r\nColumns=%d\r\nRows=%d\r\n"
           "MinX=%s\r\nMaxX=%s\r\nMinY=%s\r\nMaxY=%s\r\nResolutionX=%s\r\nResolutionY=%s\r\n[Data]\r\nDataType=FLT4BYTES\r\n"
           "MinValue=%s\r\nMaxValue=%s\r\nNoDataValue=-9999\r\nUnits=%s\r\n") % (name, ncols, nrows, X0, X1, Y0, Y1, RES, RES, min(vals), max(vals), UNITS[name])
    open(os.path.join(HERE, 'grids', name + '.grd'), 'w', newline='').write(hdr)
sql = []
for i, (name, desc) in enumerate([('e2e_temp', 'E2E synthetic temperature'), ('e2e_rain', 'E2E synthetic rainfall')]):
    lid = 9001 + i
    sql.append("INSERT INTO layers (id, name, description, type, enabled, displayname, source, classification1, classification2, domain, uid, notes, minlatitude, minlongitude, maxlatitude, maxlongitude, path_orig, environmentalvalueunits, environmentalvaluemin, environmentalvaluemax, path, displaypath) VALUES "
               "(%d, '%s', '%s', 'Environmental', true, '%s', 'ALA e2e fixture', 'Climate', 'Synthetic', 'Terrestrial', '%d', '', %s, %s, %s, %s, 'layer/%s', '%s', '', '', '', '');" % (lid, name, desc, desc, lid, Y0, X0, Y1, X1, name, UNITS[name]))
    sql.append("INSERT INTO fields (id, name, \"desc\", type, spid, indb, enabled, namesearch, defaultlayer, \"intersect\", layerbranch, analysis, addtomap) VALUES "
               "('el%d', '%s', '%s', 'e', '%d', false, true, false, true, false, false, true, true);" % (lid, desc, desc, lid))
open(os.path.join(HERE, '..', 'postgres', 'fixtures-env.sql'), 'w').write('-- generated by fixtures/make-grids.py\n' + '\n'.join(sql) + '\n')
print(ncols, nrows)
