#!/usr/bin/env python3
"""Regenerates postgres/fixtures-states.sql: ALA's contextual layer cl22 (Australian States and Territories),
simplified, so the e2e stack has real layers/fields/objects. Needs network and a throwaway PostGIS container for ST_Simplify:
  docker run -d --name e2e-simplify -e POSTGRES_PASSWORD=x postgis/postgis:16-3.4-alpine"""
import json, os, subprocess, sys, urllib.request
ALA = 'https://spatial.ala.org.au/ws'
def get(p, raw=False):
    with urllib.request.urlopen(ALA + p, timeout=60) as r:
        b = r.read().decode()
        return b if raw else json.loads(b)
def psql(sql):
    return subprocess.run(['docker', 'exec', '-i', os.environ.get('PG_CONTAINER', 'e2e-simplify'), 'psql', '-U', 'postgres', '-tA'],
                          input=sql, capture_output=True, text=True, check=True).stdout.strip()
field = get('/field/cl22')
objs = field['objects']
out = ["-- generated by fixtures/make-states.py from ALA cl22 (Australian States and Territories); simplified 0.1 deg, parts under 0.1 sq deg dropped",
       "INSERT INTO layers (id, name, description, type, enabled, displayname, source, classification1, classification2, domain, uid, notes, minlatitude, minlongitude, maxlatitude, maxlongitude, path, displaypath) VALUES "
       "(22, 'aus1', 'Australian States and Territories', 'Contextual', true, 'States and Territories', 'ALA e2e fixture', 'Political', 'Administrative', 'Terrestrial', '', '', -43.7, 112.9, -9.1, 153.7, '', '');",
       "INSERT INTO fields (id, name, \"desc\", type, spid, sid, sname, sdesc, indb, enabled, namesearch, defaultlayer, \"intersect\", layerbranch, analysis, addtomap) VALUES "
       "('cl22', 'Australian States and Territories', 'Australian States and Territories', 'c', '22', 'cl22', 'name_1', 'name_1,type_1', true, true, true, true, true, true, true, true);"]
for o in objs:
    wkt = get('/shape/wkt/' + o['pid'], raw=True)
    simp = psql("select st_astext(st_multi(st_collectionextract(st_collect(g), 3))) from (select (st_dump(st_simplifypreservetopology(st_geomfromtext($w$%s$w$, 4326), 0.1))).geom g) d "
                "where st_area(g) > case when (select count(*) from (select (st_dump(st_geomfromtext($w$%s$w$, 4326))).geom) x) > 1 then 0.1 else 0 end" % (wkt, wkt))
    if not simp:
        print('skipped (empty after simplification):', o['name'], file=sys.stderr); continue
    out.append("INSERT INTO objects (pid, id, \"desc\", name, fid, the_geom, name_id, namesearch, bbox, area_km) VALUES "
               "('%s', '%s', '%s', '%s', 'cl22', st_geomfromtext('%s', 4326), 0, true, '%s', %s);"
               % (o['pid'], o['pid'], o['description'].replace("'", "''"), o['name'].replace("'", "''"), simp, o['bbox'], o['area_km']))
    print(o['name'], len(simp), file=sys.stderr)
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'postgres', 'fixtures-states.sql'), 'w').write('\n'.join(out) + '\n')
