server {
  listen 80;
  client_max_body_size 100m;
  proxy_read_timeout 300s;
  location /geoserver/ { proxy_pass http://geoserver:8080/geoserver/; proxy_set_header Host $http_host; }
  location /ws/        { proxy_pass http://spatial-service:8080/;  proxy_set_header Host $http_host; proxy_set_header X-Forwarded-Proto $scheme; }
  location /           { proxy_pass http://spatial-hub:8080/;         proxy_set_header Host $http_host; proxy_set_header X-Forwarded-Proto $scheme; }
}
